[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spinal-tap"
dynamic = ["version"]
description = "SPINE Reconstruction Visualization Tool"
readme = "README.md"
authors = [
    {name = "DeepLearnPhysics Collaboration", email = "drielsma@stanford.edu"}
]
maintainers = [
    {name = "Francois Drielsma", email = "drielsma@stanford.edu"}
]
dependencies = [
    "spine[viz]>=1.0.1",
    "dash>=4.4.0",
    "flask>=2.0.0",
    "flask-session>=0.5.0",
    "anywidget"
]
requires-python = ">=3.10"

[project.scripts]
spinal-tap = "spinal_tap.app:main"

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "flake8",
    "pre-commit",
    "pytest",
    "pytest-cov"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
spinal_tap = ["assets/*"]

[tool.setuptools.dynamic]
version = {attr = "spinal_tap.version.__version__"}

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["spinal_tap"]
known_third_party = ["spine"]

[tool.black]
line-length = 88

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers"
testpaths = ["test"]

[tool.coverage.run]
source = ["src/spinal_tap"]
omit = [
    "*/test/*",
    "*/tests/*",
    "setup.py",
]

[tool.coverage.report]
fail_under = 100
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:",
    "@(abc\\.)?abstractmethod",
]
